89 a specific verses explanation including roots linguistics and reflections
Quran-Journey/backend pull request #132
Opened 2022-08-21 20:22 UTC by ibrahim681

2022-08-21 20:28 UTC, osamaramihafez commented
To fix conflicts, merge locally from master and accept the changes that are coming from master. You should not change the schema but can add your import inside of index.js

2022-08-22 00:06 UTC, osamaramihafez requested changes

2022-08-22 00:06 UTC, osamaramihafez commented on routes/verseInfo.js
> + *          $ref: '#/definitions/Verse'
You should create a definition specifically for this item, see #/definitions/VerseWordMeaning for an example.

2022-08-22 00:06 UTC, osamaramihafez commented on model/verseInfo.js
> +
We are returning a new type of object (which contains arrays of other objects). Please add a definition for this schema object and call it something like VerseInformation

2022-08-22 00:06 UTC, osamaramihafez commented on tests/setup.js
> +    Mufasir: [
Mufasir exists twice

2022-08-22 00:06 UTC, osamaramihafez commented on tests/setup.js
> +    RootMeaning: [
Exists twice, remove this one.

2022-08-22 00:06 UTC, osamaramihafez commented on tests/setup.js
> +    Mufasir: [
Also make sure no other tables have been duplicated.

2022-08-22 00:06 UTC, osamaramihafez commented on tests/verse-info-tests.js
> +};
Kind of petty, but try to add a newline character at the end of every document. I forget why it's important, but github keeps highlighting it anyways.

2022-08-22 00:06 UTC, osamaramihafez commented on tests/verse-info-tests.js
> +
Should we also check for an Arabic word match?

2022-08-22 00:42 UTC, ibrahim681 commented on db/schema.sql
> +    IF NOT EXISTS Surah (
not sure how to change it, I tried code>preferences>settings Prettier, but didn't seem to work🥲

2022-08-22 00:58 UTC, osamaramihafez commented on db/schema.sql
> +    IF NOT EXISTS Surah (
Don't worry, it's fine for now

2022-08-22 00:59 UTC, osamaramihafez commented on model/verseInfo.js
> +const { parseHttpResponse } = require("selenium-webdriver/http");
Don't import selenium... why? lol

2022-08-22 01:00 UTC, osamaramihafez commented on routes/verseInfo.js
> +const Ucreate = require("../model/utils");
Ucreate?

2022-08-22 01:01 UTC, osamaramihafez commented on tests/setup.js
> +            word: "بِسْمِ",
Let's put in another arabic word, perhaps "الرَّحِيمِ"

2022-08-22 01:02 UTC, osamaramihafez commented on tests/setup.js
> +    ArabicWord: [
Arabic word is still duplicated

2022-08-22 01:03 UTC, osamaramihafez submitted a review, later dismissed
Also see other comments I've made

2022-08-22 01:03 UTC, osamaramihafez commented on tests/verse-info-tests.js
> +const faker = require("faker");
Remove faker if not being used

2022-08-22 02:11 UTC, osamaramihafez commented
LGTM, ready to merge! Good work 👍🏼

2022-08-23 10:52 UTC, merged